server:
  port: 8084
  servlet:
    context-path: /images

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_IMAGES_QUERY_HOST:localhost}:3304/imagesquerydb
    username: image
    password: image2020++

events:
  amqp:
    queue: images-queue-command
  rpc:
    exchange: images-exchange-events
    queue: image-queue-query-request
    routing-key: images-events-key
    
management:
    server:
      port: 6084    