server:
  port: 8081
  servlet:
    context-path: /products

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PRODUCT_COMMAND_HOST:localhost}:3301/productcommanddb
    username: product
    password: product2020++

events:
  amqp:
    exchange: products-exchange-events
    queue: products-queue-command
    routing-key: products-command-key
  dead-letter:
    exchange: products-exchange-deadletter
    queue: products-queue-deadletter
    routing-key: products-deadletter-key
    
management:
    server:
      port: 6081